config:
  target: 'http://ec2-18-188-24-4.us-east-2.compute.amazonaws.com'
  # http:
  #   pool: 200
  phases:
    - duration: 300
      arrivalCount: 5000
  variables:
    date:
      - '2018-03-30'
      - '2018-04-01'
      - '2018-04-02'
      - '2018-04-03'
      - '2018-04-04'
  # http:
  #   pool: 200

scenarios:
  - flow:
    - loop:  
      - get:
          # url: "/restaurants/{{$loopElement}}/reservations/{{date}}"
          url: "/restaurants/restaurant11099000/reservations/{{date}}"

          # url: "/"          
      # over:
      #   - 'restaurant11099000'
      #   - 'restaurant10356000'
      #   - 'restaurant11234000'
      #   - 'restaurant10000002'
      #   - 'restaurant10340000'
      #   - 'restaurant10000001'
      #   - 'restaurant10089000'
      #   - 'restaurant10019400'
      #   - 'restaurant10020001'
      count: 100

  